# Generated by Django 6.0 on 2025-12-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_base_price_alter_booking_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='final_price',
        ),
    ]
