# Generated by Django 5.2.9 on 2025-12-14 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('booking', 'Booking Report'), ('revenue', 'Revenue Report'), ('user', 'User Report'), ('vehicle', 'Vehicle Report')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
