# Generated by Django 6.0 on 2025-12-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_latitude_vehicle_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
