# Generated by Django 6.0 on 2025-12-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image_url',
        ),
    ]
